blank_issues_enabled: true
contact_links:
  - name: TUSBAD 公式Discord
    url: https://discord.gg/rTVWQm4ykR
    about: 直接質問する場合、こちらもご利用ください。
  - name: その他のissues
    url: https://github.com/FreyCielu/TUSBAD_v12.5/issues/new
    about: テンプレートを使用しないissuesはこちらから。
